export const ministryZones = [
    "Ministry Centre Abeokuta",
    "Ministry Centre Abuja",
    "Ministry Centre Calabar",
    "Ministry Centre Ibadan",
    "Ministry Centre Warri",
    "Warri DSC Sub-Zone",
    "UK Zone 1 (Region 2)",
    "UK Zone 3 (Region 2)",
    "UK Zone 4 (Region 2)",
    "Western Europe Zone 1",
    "Western Europe Zone 2",
    "Western Europe Zone 3",
    "Western Europe Zone 4",
    "Calgary Zone",
    "USA Zone 1 (Region 1)",
    "USA Zone 2 (Region 1)",
    "USA Region 2",
    "Dallas Zone",
    "USA Region 3",
    "Hawaii and Washington States Zone",
    "South America, New Zealand and South Pacific Region",
    "Middle East and Asia Region",
    "India Zone 2",
    "Chad, Madagascar, Morocco and Comoros Region",
    "SA Zone 2",
    "SA Zone 3",
    "Capetown Zone 1",
    "Capetown Zone 2",
    "Durban Zone",
    "EWCA Zone 5",
    "EWCA Zone 6",
    "Tanzania Zone",
    "Cameroon Zone",
    "Christ Embassy Chad",
    "SA Zone 5",
    "Kenya Zone",
    "Accra Zone",
    "Lagos Zone 1",
    "Lagos Zone 2",
    "Lagos Zone 3",
    "Lagos Zone 4",
    "Lagos Zone 5",
    "Lagos Zone 6",
    "Lagos Virtual Zone",
    "Onitsha Zone",
    "Port Harcourt Zone 1",
    "Port Harcourt Zone 2",
    "Port Harcourt Zone 3",
    "Benin Zone 1",
    "Mid West Zone",
    "Abuja Zone 1",
    "Abuja Zone 2",
    "Lagos Sub Zone A",
    "Lagos Sub Zone B",
    "Lagos Sub Zone C",
    "Egbeda Sub-Zone",
    "Nigeria North West Zone 2",
    "Nigeria North West Zone 1",
    "Nigeria North Central Zone 1",
    "Nigeria North Central Zone 2",
    "Christ Embassy Jos",
    "Nigeria South East Zone 3",
    "Aba Zone",
    "Edo North & Central Zone",
    "Abakaliki Zone",
    "Nigeria South West Zone 2",
    "Nigeria South West Zone 3",
    "Nigeria South West Zone 4",
    "Ibadan Zone 1",
    "Ibadan Zone 2",
    "Ibadan East",
    "Nigeria South West Zone 5",

    // Campus Ministry Zones
    "BLW USA Region 1 Zone A",
    "BLW USA Region 1 Zone B",
    "BLW Canada Sub Region",
    "BLW UK ZONE A",
    "BLW Europe Zone 1",
    "BLW UK ZONE C",
    "BLW WALES",
    "BLW USA Region 2 Zone A",
    "BLW USA Region 2 Zone B",
    "BLW ZONE H",
    "BLW ZONE A",
    "BLW ZONE B",
    "BLW ZONE L",
    "BLW SA ZONE D",
    "BLW ZONE G",
    "BLW IRELAND",
    "BLW Zone N",
    "BLW ZONE D",
    "BLW ZONE E",
    "BLW SA ZONE C",
    "BLW SA ZONE E",
    "BLW SA Zone G",
    "BLW SA Zone H",
    "BLW SA Zone I",
    "BLW UGANDA Zone A",
    "BLW UGANDA Zone B",
    "BLW Cameroon Zone A",
    "BLW Cameroon Zone B",
    "BLW Democratic Republic of Congo, Burundi and South Sudan",
    "BLW Togo",
    "BLW Guinea Conakry",
    "BLW Gambia",
    "BLW Cote D’Ivoire",
    "BLW Liberia",
    "BLW Senegal",
    "BLW ZONE C",
    "BLW Church Zone",
    "BLW ZONE F",
    "BLW ZONE I",
    "BLW ZONE J",
    "BLW ZONE K",
    "BLW KENYA ZONE A",
    "BLW KENYA ZONE B",
    "BLW Ghana Zone A",
    "BLW Ghana Zone B",
    "BLW Ghana Zone C",
    "BLW Ghana Zone D",
    "BLW Benin Republic",
    "BLW Burkina Faso",
    "BLW SA ZONE A",
    "BLW SA ZONE B",
    "BLW SA Zone F",
    "BLW Cyprus",
    "BLW Ethiopia Group",
    "BLW ASIA",
    "BLW Tanzania",
];

export function slugifyZone(zone: string) {
    return zone
        .toLowerCase()
        .replace(/&/g, "and")
        .replace(/[’']/g, "")
        .replace(/[(),]/g, "")
        .replace(/\s+/g, "-")
        .replace(/-+/g, "-")
        .trim();
}

export const ministryZoneMap = ministryZones.reduce<Record<string, string>>(
    (acc, zone) => {
        acc[slugifyZone(zone)] = zone;
        return acc;
    },
    {},
);
